version: "2"
services:
  app:
    build: ./app
    links:
      - mysql_database
    ports:
      - "5000:5000"
  mysql_database:
    image: mysql:5.7
    ports:
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro